ceilometer-agent-central has been replaced by ceilometer-polling
The ceilometer-agent-central and ceilometer-agent-compute
services are now completely removed from the liberty release
of ceilometer. The new implementation is to use
ceilometer-polling and call the respective pollsters by
namespace.

Change-Id: I3af6fe9cc9c5b0fcf0406f89f402cbd1a31f66c4
Closes-Bug: 1606787

diff --git a/ocf/openstack/ceilometer-polling b/ocf/openstack/ceilometer-polling
--- a/ocf/openstack/ceilometer-polling
+++ b/ocf/openstack/ceilometer-polling
@@ -1,9 +1,9 @@
 #!/bin/sh
 #
 #
-# OpenStack Ceilometer Central Agent Service (ceilometer-agent-central)
+# OpenStack Ceilometer Polling Agent Service (ceilometer-polling)
 #
-# Description: Manages an OpenStack Ceilometer Central Agent Service (ceilometer-agent-central) process as an HA resource
+# Description: Manages an OpenStack Ceilometer Polling Agent Service (ceilometer-polling) process as an HA resource
 #
 # Authors: Emilien Macchi
 # Mainly inspired by the Nova Scheduler resource agent written by Sebastien Han
@@ -32,7 +32,8 @@
 
 # Fill in some defaults if no values are specified
 
-OCF_RESKEY_binary_default="ceilometer-agent-central"
+OCF_RESKEY_binary_default="ceilometer-polling"
+OCF_RESKEY_additional_parameters=" --polling-namespaces central"
 OCF_RESKEY_config_default="/etc/ceilometer/ceilometer.conf"
 OCF_RESKEY_user_default="ceilometer"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
@@ -50,7 +51,7 @@ usage() {
     cat <<UEND
         usage: $0 (start|stop|validate-all|meta-data|status|monitor)
 
-        $0 manages an OpenStack Ceilometer Central Agent Service (ceilometer-agent-central) process as an HA resource
+        $0 manages an OpenStack Ceilometer Polling Agent Service (ceilometer-polling) process as an HA resource
 
         The 'start' operation starts the scheduler service.
         The 'stop' operation stops the scheduler service.
@@ -66,46 +67,46 @@ meta_data() {
     cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="ceilometer-agent-central">
+<resource-agent name="ceilometer-polling">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource agent for the OpenStack Ceilometer Central Agent Service (ceilometer-agent-central)
-May manage a ceilometer-agent-central instance or a clone set that
-creates a distributed ceilometer-agent-central cluster.
+Resource agent for the OpenStack Ceilometer Polling Agent Service (ceilometer-polling)
+May manage a ceilometer-polling instance or a clone set that
+creates a distributed ceilometer-polling cluster.
 </longdesc>
-<shortdesc lang="en">Manages the OpenStack Ceilometer Central Agent Service (ceilometer-agent-central)</shortdesc>
+<shortdesc lang="en">Manages the OpenStack Ceilometer Polling Agent Service (ceilometer-polling)</shortdesc>
 <parameters>
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Ceilometer Central Agent server binary (ceilometer-agent-central)
+Location of the OpenStack Ceilometer Polling Agent server binary (ceilometer-polling)
 </longdesc>
-<shortdesc lang="en">OpenStack Ceilometer Central Agent server binary (ceilometer-agent-central)</shortdesc>
+<shortdesc lang="en">OpenStack Ceilometer Polling Agent server binary (ceilometer-polling)</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
 <parameter name="config" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Ceilometer Central Agent Service (ceilometer-agent-central) configuration file
+Location of the OpenStack Ceilometer Polling Agent Service (ceilometer-polling) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack Ceilometer Central Agent (ceilometer-agent-central registry) config file</shortdesc>
+<shortdesc lang="en">OpenStack Ceilometer Polling Agent (ceilometer-polling registry) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
 </parameter>
 
 <parameter name="user" unique="0" required="0">
 <longdesc lang="en">
-User running OpenStack Ceilometer Central Agent Service (ceilometer-agent-central)
+User running OpenStack Ceilometer Polling Agent Service (ceilometer-polling)
 </longdesc>
-<shortdesc lang="en">OpenStack Ceilometer Central Agent Service (ceilometer-agent-central) user</shortdesc>
+<shortdesc lang="en">OpenStack Ceilometer Polling Agent Service (ceilometer-polling) user</shortdesc>
 <content type="string" default="${OCF_RESKEY_user_default}" />
 </parameter>
 
 <parameter name="pid" unique="0" required="0">
 <longdesc lang="en">
-The pid file to use for this OpenStack Ceilometer Central Agent Service (ceilometer-agent-central) instance
+The pid file to use for this OpenStack Ceilometer Polling Agent Service (ceilometer-polling) instance
 </longdesc>
-<shortdesc lang="en">OpenStack Ceilometer Central Agent Service (ceilometer-agent-central) pid file</shortdesc>
+<shortdesc lang="en">OpenStack Ceilometer Polling Agent Service (ceilometer-polling) pid file</shortdesc>
 <content type="string" default="${OCF_RESKEY_pid_default}" />
 </parameter>
 
@@ -120,9 +121,9 @@ The listening port number of the AMQP server. Use for monitoring purposes
 
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
-Additional parameters to pass on to the OpenStack Ceilometer Central Agent Service (ceilometer-agent-central)
+Additional parameters to pass on to the OpenStack Ceilometer Polling Agent Service (ceilometer-polling)
 </longdesc>
-<shortdesc lang="en">Additional parameters for ceilometer-agent-central</shortdesc>
+<shortdesc lang="en">Additional parameters for ceilometer-polling</shortdesc>
 <content type="string" />
 </parameter>
 
@@ -143,7 +144,7 @@ END
 #######################################################################
 # Functions invoked by resource manager actions
 
-ceilometer_agent_central_check_port() {
+ceilometer_polling_check_port() {
 # This function has been taken from the squid RA and improved a bit
 # The length of the integer must be 4
 # Examples of valid port: "1080", "0080"
@@ -151,7 +152,7 @@ ceilometer_agent_central_check_port() {
 
     local int
     local cnt
-    
+
     int="$1"
     cnt=${#int}
     echo $int |egrep -qx '[0-9]+(:[0-9]+)?(,[0-9]+(:[0-9]+)?)*'
@@ -162,13 +163,13 @@ ceilometer_agent_central_check_port() {
     fi
 }
 
-ceilometer_agent_central_validate() {
+ceilometer_polling_validate() {
     local rc
 
     check_binary $OCF_RESKEY_binary
     check_binary netstat
-    ceilometer_agent_central_check_port $OCF_RESKEY_amqp_server_port
-    
+    ceilometer_polling_check_port $OCF_RESKEY_amqp_server_port
+
     # A config file on shared storage that is not available
     # during probes is OK.
     if [ ! -f $OCF_RESKEY_config ]; then
@@ -189,12 +190,12 @@ ceilometer_agent_central_validate() {
     true
 }
 
-ceilometer_agent_central_status() {
+ceilometer_polling_status() {
     local pid
     local rc
 
     if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack Ceilometer Central Agent (ceilometer-agent-central) is not running"
+        ocf_log info "OpenStack Ceilometer Polling Agent (ceilometer-polling) is not running"
         return $OCF_NOT_RUNNING
     else
         pid=`cat $OCF_RESKEY_pid`
@@ -205,17 +206,17 @@ ceilometer_agent_central_status() {
     if [ $rc -eq 0 ]; then
         return $OCF_SUCCESS
     else
-        ocf_log info "Old PID file found, but OpenStack Ceilometer Central Agent (ceilometer-agent-central) is not running"
+        ocf_log info "Old PID file found, but OpenStack Ceilometer Polling Agent (ceilometer-polling) is not running"
         return $OCF_NOT_RUNNING
     fi
 }
 
-ceilometer_agent_central_monitor() {
+ceilometer_polling_monitor() {
     local rc
     local pid
     local scheduler_amqp_check
 
-    ceilometer_agent_central_status
+    ceilometer_polling_status
     rc=$?
 
     # If status returned anything but success, return that immediately
@@ -233,51 +234,51 @@ ceilometer_agent_central_monitor() {
         return $OCF_NOT_RUNNING
         fi
 
-    ocf_log debug "OpenStack Ceilometer Central Agent (ceilometer-agent-central) monitor succeeded"
+    ocf_log debug "OpenStack Ceilometer Polling Agent (ceilometer-polling) monitor succeeded"
     return $OCF_SUCCESS
 }
 
-ceilometer_agent_central_start() {
+ceilometer_polling_start() {
     local rc
 
     service ceilometer-agent-central stop >> /dev/null 2>&1
 
-    ceilometer_agent_central_status
+    ceilometer_polling_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack Ceilometer Central Agent (ceilometer-agent-central) already running"
+        ocf_log info "OpenStack Ceilometer Polling Agent (ceilometer-polling) already running"
         return $OCF_SUCCESS
     fi
 
-    # run the actual ceilometer-agent-central daemon. Don't use ocf_run as we're sending the tool's output
+    # run the actual ceilometer-polling daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
     su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
        $OCF_RESKEY_additional_parameters"' >> /dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
 
     # Spin waiting for the server to come up.
     while true; do
-    ceilometer_agent_central_monitor
+    ceilometer_polling_monitor
     rc=$?
     [ $rc -eq $OCF_SUCCESS ] && break
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack Ceilometer Central Agent (ceilometer-agent-central) start failed"
+        ocf_log err "OpenStack Ceilometer Polling Agent (ceilometer-polling) start failed"
         exit $OCF_ERR_GENERIC
     fi
     sleep 1
     done
 
-    ocf_log info "OpenStack Ceilometer Central Agent (ceilometer-agent-central) started"
+    ocf_log info "OpenStack Ceilometer Polling Agent (ceilometer-polling) started"
     return $OCF_SUCCESS
 }
 
-ceilometer_agent_central_stop() {
+ceilometer_polling_stop() {
     local rc
     local pid
 
-    ceilometer_agent_central_status
+    ceilometer_polling_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
-        ocf_log info "OpenStack Ceilometer Central Agent (ceilometer-agent-central) already stopped"
+        ocf_log info "OpenStack Ceilometer Polling Agent (ceilometer-polling) already stopped"
         return $OCF_SUCCESS
     fi
 
@@ -286,7 +287,7 @@ ceilometer_agent_central_stop() {
     ocf_run kill -s TERM $pid
     rc=$?
     if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack Ceilometer Central Agent (ceilometer-agent-central) couldn't be stopped"
+        ocf_log err "OpenStack Ceilometer Polling Agent (ceilometer-polling) couldn't be stopped"
         exit $OCF_ERR_GENERIC
     fi
 
@@ -297,26 +298,26 @@ ceilometer_agent_central_stop() {
     fi
     count=0
     while [ $count -lt $shutdown_timeout ]; do
-        ceilometer_agent_central_status
+        ceilometer_polling_status
         rc=$?
         if [ $rc -eq $OCF_NOT_RUNNING ]; then
             break
         fi
         count=`expr $count + 1`
         sleep 1
-        ocf_log debug "OpenStack Ceilometer Central Agent (ceilometer-agent-central) still hasn't stopped yet. Waiting ..."
+        ocf_log debug "OpenStack Ceilometer Polling Agent (ceilometer-polling) still hasn't stopped yet. Waiting ..."
     done
 
-    ceilometer_agent_central_status
+    ceilometer_polling_status
     rc=$?
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
         # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack Ceilometer Central Agent (ceilometer-agent-central) failed to stop after ${shutdown_timeout}s \
+        ocf_log info "OpenStack Ceilometer Polling Agent (ceilometer-polling) failed to stop after ${shutdown_timeout}s \
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
 
-    ocf_log info "OpenStack Ceilometer Central Agent (ceilometer-agent-central) stopped"
+    ocf_log info "OpenStack Ceilometer Polling Agent (ceilometer-polling) stopped"
 
     rm -f $OCF_RESKEY_pid
 
@@ -333,14 +334,14 @@ case "$1" in
 esac
 
 # Anything except meta-data and help must pass validation
-ceilometer_agent_central_validate || exit $?
+ceilometer_polling_validate || exit $?
 
 # What kind of method was invoked?
 case "$1" in
-  start) ceilometer_agent_central_start;;
-  stop) ceilometer_agent_central_stop;;
-  status) ceilometer_agent_central_status;;
-  monitor) ceilometer_agent_central_monitor;;
+  start) ceilometer_polling_start;;
+  stop) ceilometer_polling_stop;;
+  status) ceilometer_polling_status;;
+  monitor) ceilometer_polling_monitor;;
   validate-all) ;;
   *) usage
                 exit $OCF_ERR_UNIMPLEMENTED;;
